name: senior
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  camera: ^0.11.1+2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/objects.png
    - assets/images/task.png
    - assets/images/NoPath.png
    - assets/images/Path.png
    - assets/images/chat.png
